#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    dpkg-trigger update-fixperms
}

case "$1" in
    purge)
        remove_action

        SERVICE_XPATH_NAME="tgt"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if omv_config_exists "${SERVICE_XPATH}"; then
           omv_config_delete "${SERVICE_XPATH}"
        fi
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
       echo "postrm called with unknown argument '$1'" >&2
       exit 1
    ;;
esac

#DEBHELPER#

exit 0
